const test = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync, existsSync } = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const root = path.resolve(__dirname, '..');
const read = (rel) => readFileSync(path.join(root, rel), 'utf8');
const html = read('index.html');
const sw = read('sw.js');
const buildInfoSrc = read('build-info.js');
const stampSrc = read('scripts/stamp-build.mjs');
const hookSrc = read('.githooks/pre-commit');
const pkg = JSON.parse(read('package.json'));

function loadBuildInfo() {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(buildInfoSrc, sandbox, { filename: 'build-info.js' });
  return sandbox.window.MINI_BUILD_INFO;
}

test('package version is the human semantic version 2.13.0', () => {
  assert.equal(pkg.version, '2.13.0');
  assert.match(buildInfoSrc, /version:\s*"2\.13\.0"/);
  assert.match(sw, /asistencia-v2\.13\.0/);
});

test('Settings/System shows a visible Mini version and build date', () => {
  assert.match(html, /id="mini-version"/);
  assert.match(html, /id="mini-build-date"/);
  assert.match(html, /Mini versi/);
  assert.match(html, /Actualizado/);
  assert.match(html, /renderBuildInfo\(\)/);
  assert.match(html, /formatBuildDateEsDo/);
});

test('build date uses human-friendly es-DO formatting', () => {
  assert.match(html, /es-DO/);
  assert.match(html, /Intl\.DateTimeFormat\(['"]es-DO['"]/);
});

test('build-info.js has a deterministic generated shape with ISO timestamp', () => {
  const info = loadBuildInfo();
  assert.equal(info.version, pkg.version);
  assert.match(info.buildId, /^\d{8}-\d{6}-\d{3}$/);
  assert.ok(!Number.isNaN(Date.parse(info.updatedAt)), 'updatedAt must be a valid date');
  assert.equal(new Date(info.updatedAt).toISOString(), info.updatedAt);
  assert.match(buildInfoSrc, /GENERATED by scripts\/stamp-build\.mjs/);
  assert.match(buildInfoSrc, /window\.MINI_BUILD_INFO\s*=/);
});

test('index.html loads build-info.js before the main inline app script', () => {
  const tag = '<script src="./build-info.js"></script>';
  const tagIndex = html.indexOf(tag);
  assert.ok(tagIndex > 0, 'build-info.js script tag must exist');
  const bulkIndex = html.indexOf('<script src="./bulk-actions.js"></script>');
  assert.ok(tagIndex > bulkIndex, 'build-info.js must load after the other vendor modules');
  const inlineIndex = html.indexOf('<script>', tagIndex);
  assert.ok(inlineIndex > tagIndex, 'build-info.js must load before the main inline app script');
});

test('service worker uses a unique cache name and precaches build-info.js', () => {
  assert.match(sw, /^const CACHE_VERSION = 'asistencia-v2\.13\.0-.+';/m);
  assert.match(sw, /'\.\/build-info\.js'/);
  // Offline behavior is preserved: install precache, old-cache cleanup, fetch handler.
  assert.match(sw, /self\.addEventListener\('install'/);
  assert.match(sw, /self\.addEventListener\('activate'/);
  assert.match(sw, /self\.addEventListener\('fetch'/);
  assert.match(sw, /caches\.open\(CACHE_VERSION\)/);
});

test('initPWA checks for updates without a stale SW cache', () => {
  assert.match(html, /register\(['"]\.\/sw\.js['"],\s*\{\s*updateViaCache:\s*['"]none['"]\s*\}/);
  assert.match(html, /registration\.update\(\)/);
});

test('initPWA reloads once when a newer worker takes control (no loops)', () => {
  assert.match(html, /controllerchange/);
  assert.match(html, /location\.reload\(\)/);
  assert.match(html, /pwaUpdateReloaded/);
  assert.match(html, /if\s*\(\s*pwaUpdateReloaded\s*\)\s*return/);
  assert.match(html, /pwaUpdateReloaded\s*=\s*true/);
});

test('manual clearCacheAndReload remains as fallback and keeps app data', () => {
  const start = html.indexOf('async function clearCacheAndReload()');
  assert.ok(start > 0, 'clearCacheAndReload must still exist');
  const body = html.slice(start, html.indexOf('function installPWA()', start));
  assert.match(body, /location\.reload\(\)/);
  assert.match(body, /caches\.delete/);
  assert.doesNotMatch(body, /localStorage\.clear/);
  assert.doesNotMatch(body, /localStorage\.removeItem\('users'\)/);
  assert.doesNotMatch(body, /localStorage\.removeItem\('attendance'\)/);
  assert.doesNotMatch(body, /indexedDB\.deleteDatabase/);
  assert.doesNotMatch(body, /deleteDatabase/);
});

test('stamp script only rewrites generated stamp fields and is rerunnable', () => {
  assert.ok(existsSync(path.join(root, 'scripts/stamp-build.mjs')));
  assert.match(stampSrc, /package\.json/);
  assert.match(stampSrc, /build-info\.js/);
  assert.match(stampSrc, /CACHE_VERSION/);
  assert.match(stampSrc, /toISOString\(\)/);
  assert.match(stampSrc, /MINI_BUILD_TIME/);
  // Narrow replacement: only the CACHE_VERSION line, never the precache list.
  assert.match(stampSrc, /const CACHE_VERSION/);
  assert.doesNotMatch(stampSrc, /PRECACHE_ASSETS/);
});

test('pre-commit hook stamps and stages ONLY the generated files', () => {
  assert.ok(existsSync(path.join(root, '.githooks/pre-commit')));
  assert.match(hookSrc, /node scripts\/stamp-build\.mjs/);
  assert.match(hookSrc, /git add build-info\.js sw\.js/);
  assert.doesNotMatch(hookSrc, /git commit/);
  assert.doesNotMatch(hookSrc, /git push/);
  assert.doesNotMatch(hookSrc, /git add -A/);
  assert.doesNotMatch(hookSrc, /git add \./);
});

test('package.json wires stamp on build but keeps pretest stamp-free', () => {
  assert.match(pkg.scripts.build, /node scripts\/stamp-build\.mjs/);
  assert.match(pkg.scripts.build, /tsc/);
  assert.equal(pkg.scripts.pretest, 'tsc');
  assert.doesNotMatch(pkg.scripts.pretest, /stamp-build/);
  assert.match(pkg.scripts.prepare, /core\.hooksPath/);
  assert.match(pkg.scripts.prepare, /\.githooks/);
});
