// scripts/stamp-build.mjs
// Regenerates build-info.js and bumps the service-worker cache version.
// Deterministic shape, safe to rerun: only rewrites generated stamp fields.
//
// Override the timestamp deterministically with:
//   MINI_BUILD_TIME=2026-09-07T07:21:00.123Z node scripts/stamp-build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const pkgPath = path.join(root, 'package.json');
const buildInfoPath = path.join(root, 'build-info.js');
const swPath = path.join(root, 'sw.js');

function resolveBuildDate() {
  const override = process.env.MINI_BUILD_TIME;
  if (override) {
    const parsed = new Date(override);
    if (!Number.isNaN(parsed.getTime())) return parsed;
  }
  return new Date();
}

function toBuildId(date) {
  const digits = date.toISOString().replace(/\D/g, '');
  return `${digits.slice(0, 8)}-${digits.slice(8, 14)}-${digits.slice(14, 17)}`;
}

function buildInfoSource({ version, buildId, updatedAt }) {
  return (
    `// GENERATED by scripts/stamp-build.mjs - do not edit by hand.\n` +
    `window.MINI_BUILD_INFO = {\n` +
    `  version: ${JSON.stringify(version)},\n` +
    `  buildId: ${JSON.stringify(buildId)},\n` +
    `  updatedAt: ${JSON.stringify(updatedAt)}\n` +
    `};\n`
  );
}

try {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const version = pkg.version;
  if (!version) throw new Error('package.json is missing "version"');

  const now = resolveBuildDate();
  const updatedAt = now.toISOString();
  const buildId = toBuildId(now);
  const cacheVersion = `asistencia-v${version}-${buildId}`;

  writeFileSync(buildInfoPath, buildInfoSource({ version, buildId, updatedAt }), 'utf8');

  const sw = readFileSync(swPath, 'utf8');
  const pattern = /^const CACHE_VERSION = '[^']*';/m;
  if (!pattern.test(sw)) throw new Error('sw.js is missing the CACHE_VERSION stamp line');
  const nextSw = sw.replace(pattern, `const CACHE_VERSION = '${cacheVersion}';`);
  writeFileSync(swPath, nextSw, 'utf8');

  console.log(`stamped build-info.js v${version} ${buildId} ${updatedAt}`);
  console.log(`stamped sw.js CACHE_VERSION=${cacheVersion}`);
} catch (error) {
  console.error(`stamp-build failed: ${error instanceof Error ? error.message : error}`);
  process.exit(1);
}
